import { accounts } from "@/db/schema/accounts";
import {
  favoriteNationalOpportunities,
  favoriteNationalOpportunitiesRelations,
} from "@/db/schema/favorite-national-opportunities";
import {
  favoriteOpportunities,
  favoriteOpportunitiesRelations,
} from "@/db/schema/favorite-opportunities";
import { nationalOpportunities } from "@/db/schema/national-opportunities";
import { opportunities } from "@/db/schema/opportunities";
import { sessions } from "@/db/schema/sessions";
import { users } from "@/db/schema/users";
import { verifications } from "@/db/schema/verifications";
import {
  applicationFees,
  applicationLinkAssessments,
  applicationRounds,
  auditEvents,
  editionSourceDocuments,
  editions,
  eligibilityAgeRules,
  eligibilityProfiles,
  extractionRuns,
  fieldApplicabilityAssessments,
  fieldAssertions,
  fieldDisplayProjections,
  fieldSemanticStates,
  fieldSourceCoverage,
  idempotencyRequests,
  materialChangeEvents,
  organizations,
  outboxEvents,
  productFitAssessments,
  programs,
  publicationGateDecisions,
  publicationVersions,
  recrawlJobs,
  resolvedFields,
  reviewerCorrections,
  reviewTasks,
  snapshots,
  sourceDocuments,
  sourceRuns,
  sources,
} from "./ingestion";

export const schema = {
  opportunities,
  accounts,
  sessions,
  users,
  verifications,
  favoriteOpportunities,
  favoriteOpportunitiesRelations,
  favoriteNationalOpportunities,
  favoriteNationalOpportunitiesRelations,
  nationalOpportunities,
  auditEvents,
  organizations,
  sources,
  sourceDocuments,
  snapshots,
  extractionRuns,
  fieldAssertions,
  fieldApplicabilityAssessments,
  fieldDisplayProjections,
  fieldSemanticStates,
  fieldSourceCoverage,
  idempotencyRequests,
  resolvedFields,
  programs,
  editions,
  editionSourceDocuments,
  applicationRounds,
  eligibilityProfiles,
  eligibilityAgeRules,
  applicationFees,
  applicationLinkAssessments,
  productFitAssessments,
  reviewTasks,
  reviewerCorrections,
  publicationVersions,
  publicationGateDecisions,
  materialChangeEvents,
  outboxEvents,
  recrawlJobs,
  sourceRuns,
};
